packages:
  - "apps/*"
  - "packages/create-oberon-app"
  - "packages/oberoncms/*"
  - "packages/plugins/*"
  - "packages/tohuhono/*"
  - "recipes/*"
useNodeVersion: "24.13.0"
allowBuilds:
  bufferutil: true
  esbuild: true
  esbuild@0.27.0: true
  msgpackr-extract: true
  sharp: true
  unrs-resolver: true
