packages:
  - "apps/*"
  - "config/*"
  - "packages/create-oberon-app"
  - "packages/oberoncms/*"
  - "packages/plugins/*"
  - "packages/tohuhono/*"
  - "recipes/*"
  - "tests"
useNodeVersion: "24.13.0"
allowBuilds:
  bufferutil: true
  esbuild: true
  msgpackr-extract: true
  sharp: true
  unrs-resolver: true
