name: Promote

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      project:
        required: true
        type: string
      staging_url:
        required: true
        type: string
      production_url:
        required: true
        type: string
    secrets:
      VERCEL_API_TOKEN:
        required: true
      VERCEL_ORG_ID:
        required: true
      VERCEL_PROJECT_ID:
        required: true

run-name: ${{ format('Promote {0}', inputs.project ) }}

jobs:
  promote:
    environment: ${{ format('{0}-{1}', inputs.environment, inputs.project) }}
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_API_TOKEN: ${{ secrets.VERCEL_API_TOKEN }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Alias build to production
        run: |
          npx vercel alias ${{ inputs.staging_url }} ${{ inputs.production_url }} --token=${{ secrets.VERCEL_API_TOKEN }} --scope ${{ vars.VERCEL_SCOPE }}
