name: CI

on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  changed-packages:
    name: Determine which packages changed
    uses: ./.github/workflows/changed-packages.yml

  deploy_tohuhono:
    name: Tohuhono
    needs: [changed-packages]
    if: ${{ contains(needs.changed-packages.outputs.changed_packages, '@oberon/tohuhono') }}
    uses: ./.github/workflows/deploy.yml
    with:
      environment: "${{ ( github.ref == 'refs/heads/main' && github.event_name == 'push' ) && 'production' || 'preview' }}"
      project: tohuhono
    secrets:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_API_TOKEN: ${{ secrets.VERCEL_API_TOKEN }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

  deploy_rich_text:
    name: Rich Text
    needs: [changed-packages]
    if: ${{ contains(needs.changed-packages.outputs.changed_packages, '@oberon/rich-text-demo') }}
    uses: ./.github/workflows/deploy.yml
    with:
      environment: "${{ ( github.ref == 'refs/heads/main' && github.event_name == 'push' ) && 'production' || 'preview' }}"
      project: rich_text
    secrets:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_API_TOKEN: ${{ secrets.VERCEL_API_TOKEN }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

  deploy_playground:
    name: Oberon Playground
    needs: [changed-packages]
    if: ${{ contains(needs.changed-packages.outputs.changed_packages, 'oberon-cms-example') }}
    uses: ./.github/workflows/deploy.yml
    with:
      environment: "${{ ( github.ref == 'refs/heads/main' && github.event_name == 'push' ) && 'production' || 'preview' }}"
      project: playground
    secrets:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_API_TOKEN: ${{ secrets.VERCEL_API_TOKEN }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      TURSO_URL: ${{ secrets.TURSO_URL }}
      TURSO_TOKEN: ${{ secrets.TURSO_TOKEN }}

  deploy-status:
    name: Deploy Status
    needs: [deploy_tohuhono, deploy_rich_text, deploy_playground]
    if: always() && !contains(needs.*.result, 'cancelled')
    runs-on: ubuntu-latest
    env:
      STATUS: "${{ contains(needs.*.result, 'failure') && 'failed' || 'passed' }}"
      MESSAGE: |
        Latest deployments available at: 
        ${{ needs.deploy_tohuhono.outputs.url && format('[tohuhono]({0}) ', needs.deploy_tohuhono.outputs.url) }}
        ${{ needs.deploy_rich_text.outputs.url && format('[rich text]({0}) ', needs.deploy_rich_text.outputs.url) }}
        ${{ needs.deploy_playground.outputs.url && format('[developer playground]({0}) ', needs.deploy_playground.outputs.url) }}
    steps:
      - name: Add preview URL to job summary
        run: |
          echo "${{ env.STATUS == 'failed' && 'Deploy Failed' || env.MESSAGE }}" >> $GITHUB_STEP_SUMMARY
      - name: Failing deploy
        if: ${{ env.STATUS == 'failed' }}
        run: exit 1

  # smoke-test:
  #   name: Smoke Test
  #   needs: [deploy]
  #   uses: ./.github/workflows/playwright.yml
  #   with:
  #     url: ${{ needs.deploy.outputs.url }}
  #     tag: "@smoke"

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-
      - name: Use pNpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "pnpm"
      - name: Install
        run: pnpm i
      - name: Prettier
        run: pnpm prettier
      - name: Lint
        run: pnpm lint --cache-dir=.turbo
      - name: Types
        run: pnpm tsc --cache-dir=.turbo

  unit-test:
    name: Unit Test
    uses: ./.github/workflows/jest.yml

  #  component-test:
  #    name: Component Test
  #    uses: ./.github/workflows/playwright.yml
  #    with:
  #      url: ""
  #      tag: "@component"

  test-status:
    name: Test Status
    #    needs: [smoke-test, lint, unit-test, component-test]
    needs: [deploy-status, lint, unit-test]
    if: always() && !contains(needs.*.result, 'cancelled')
    runs-on: ubuntu-latest
    env:
      STATUS: "${{ ( contains(needs.*.result, 'failure') || contains(needs.*.result, 'skipped') ) && 'failed' || 'passed'}}"
    steps:
      - name: Failing deploy
        if: ${{ env.STATUS == 'failed' }}
        run: exit 1

  promote_tohuhono:
    name: Tohuhono
    needs: [deploy_tohuhono, test-status]
    if: |
      always() && 
      github.ref == 'refs/heads/main' &&
      !contains(needs.*.result, 'cancelled') &&
      !contains(needs.*.result, 'failure') &&
      needs.deploy_tohuhono.result == 'success'
    uses: ./.github/workflows/promote.yml
    secrets:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_API_TOKEN: ${{ secrets.VERCEL_API_TOKEN }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    with:
      environment: production
      project: tohuhono
      staging_url: ${{ needs.deploy_tohuhono.outputs.url }}
      production_url: www.tohuhono.com

  promote_rich_text:
    name: Rich Text
    needs: [deploy_rich_text, test-status]
    if: |
      always() && 
      github.ref == 'refs/heads/main' &&
      !contains(needs.*.result, 'cancelled') &&
      !contains(needs.*.result, 'failure') &&
      needs.deploy_rich_text.result == 'success'
    uses: ./.github/workflows/promote.yml
    secrets:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_API_TOKEN: ${{ secrets.VERCEL_API_TOKEN }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    with:
      environment: production
      project: rich_text
      staging_url: ${{ needs.deploy_rich_text.outputs.url }}
      production_url: puck-rich-text.tohuhono.com

  promote_playground:
    name: Oberon Playground
    needs: [deploy_playground, test-status]
    if: |
      always() && 
      github.ref == 'refs/heads/main' &&
      !contains(needs.*.result, 'cancelled') &&
      !contains(needs.*.result, 'failure') &&
      needs.deploy_playground.result == 'success'
    uses: ./.github/workflows/promote.yml
    secrets:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_API_TOKEN: ${{ secrets.VERCEL_API_TOKEN }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    with:
      environment: production
      project: playground
      staging_url: ${{ needs.deploy_playground.outputs.url }}
      production_url: playground.tohuhono.com
