name: Add contributors

on:
  push:
    branches:
      - changeset-release/main

permissions:
  contents: read

jobs:
  add-contributors:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub App token
        uses: actions/create-github-app-token@fee1f7d63c2ff003460e3d139729b119787bc349 # v2.2.2
        id: app-token
        with:
          app-id: ${{ vars.CHANGESET_APP_ID }}
          private-key: ${{ secrets.CHANGESET_APP_SECRET }}
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          token: ${{ steps.app-token.outputs.token }}
      - name: Use Node.js
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version: "24.x"
          package-manager-cache: false
      - name: Corepack
        run: corepack enable pnpm
      - name: Update contributors
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          CONTRIBUTORS_REPO: Tohuhono/Oberon
          CONTRIBUTORS_HEADING: "## Contributors"
          CONTRIBUTORS_README: ./README.md
        run: pnpm dlx tsx@4.21.0 dev/scripts/scripts/update-contributors.ts
