name: Neon Cleanup
on:
  pull_request:
    types: [closed]

jobs:
  delete-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Install Neon CLI
        run: npm install -g neonctl@latest

      - name: Delete Branch
        env:
          NEON_API_KEY: ${{ secrets.NEON_API_KEY }}
        run: |
          BRANCH_NAME="preview/pr-${{ github.event.number }}"
          neonctl branches delete $BRANCH_NAME --project-id ${{ vars.NEON_PROJECT_ID }}
