name: Preview CI

on:
  pull_request_target:
    branches:
      - main

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label }}"
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/call/ci.yml
    with:
      environment: preview
      repository: ${{ github.event.pull_request.head.repo.full_name }}
      ref: ${{ github.event.pull_request.head.ref }}
    secrets:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_API_TOKEN: ${{ secrets.VERCEL_API_TOKEN }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      TURSO_URL: ${{ secrets.TURSO_URL }}
      TURSO_TOKEN: ${{ secrets.TURSO_TOKEN }}
