/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as SplatRouteImport } from "./routes/$"
import { Route as rootRouteImport } from "./routes/__root"
import { Route as CmsSplatRouteImport } from "./routes/cms/$"
import { Route as CmsApiSplatRouteImport } from "./routes/cms/api/$"

const SplatRoute = SplatRouteImport.update({
  id: "/$",
  path: "/$",
  getParentRoute: () => rootRouteImport,
} as any)
const CmsSplatRoute = CmsSplatRouteImport.update({
  id: "/cms/$",
  path: "/cms/$",
  getParentRoute: () => rootRouteImport,
} as any)
const CmsApiSplatRoute = CmsApiSplatRouteImport.update({
  id: "/cms/api/$",
  path: "/cms/api/$",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/$": typeof SplatRoute
  "/cms/$": typeof CmsSplatRoute
  "/cms/api/$": typeof CmsApiSplatRoute
}
export interface FileRoutesByTo {
  "/$": typeof SplatRoute
  "/cms/$": typeof CmsSplatRoute
  "/cms/api/$": typeof CmsApiSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/$": typeof SplatRoute
  "/cms/$": typeof CmsSplatRoute
  "/cms/api/$": typeof CmsApiSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/$" | "/cms/$" | "/cms/api/$"
  fileRoutesByTo: FileRoutesByTo
  to: "/$" | "/cms/$" | "/cms/api/$"
  id: "__root__" | "/$" | "/cms/$" | "/cms/api/$"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SplatRoute: typeof SplatRoute
  CmsSplatRoute: typeof CmsSplatRoute
  CmsApiSplatRoute: typeof CmsApiSplatRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/$": {
      id: "/$"
      path: "/$"
      fullPath: "/$"
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/cms/$": {
      id: "/cms/$"
      path: "/cms/$"
      fullPath: "/cms/$"
      preLoaderRoute: typeof CmsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/cms/api/$": {
      id: "/cms/api/$"
      path: "/cms/api/$"
      fullPath: "/cms/api/$"
      preLoaderRoute: typeof CmsApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  SplatRoute: SplatRoute,
  CmsSplatRoute: CmsSplatRoute,
  CmsApiSplatRoute: CmsApiSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { createStart } from "@tanstack/react-start"

import type { getRouter } from "./router.tsx"
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
