/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as CmsRouteImport } from "./routes/cms"
import { Route as CmsApiSplatRouteImport } from "./routes/cms/api/$"
import { Route as IndexRouteImport } from "./routes/index"

const CmsRoute = CmsRouteImport.update({
  id: "/cms",
  path: "/cms",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const CmsApiSplatRoute = CmsApiSplatRouteImport.update({
  id: "/api/$",
  path: "/api/$",
  getParentRoute: () => CmsRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/cms": typeof CmsRouteWithChildren
  "/cms/api/$": typeof CmsApiSplatRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/cms": typeof CmsRouteWithChildren
  "/cms/api/$": typeof CmsApiSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/cms": typeof CmsRouteWithChildren
  "/cms/api/$": typeof CmsApiSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/" | "/cms" | "/cms/api/$"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/cms" | "/cms/api/$"
  id: "__root__" | "/" | "/cms" | "/cms/api/$"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CmsRoute: typeof CmsRouteWithChildren
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/cms": {
      id: "/cms"
      path: "/cms"
      fullPath: "/cms"
      preLoaderRoute: typeof CmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/cms/api/$": {
      id: "/cms/api/$"
      path: "/api/$"
      fullPath: "/cms/api/$"
      preLoaderRoute: typeof CmsApiSplatRouteImport
      parentRoute: typeof CmsRoute
    }
  }
}

interface CmsRouteChildren {
  CmsApiSplatRoute: typeof CmsApiSplatRoute
}

const CmsRouteChildren: CmsRouteChildren = {
  CmsApiSplatRoute: CmsApiSplatRoute,
}

const CmsRouteWithChildren = CmsRoute._addFileChildren(CmsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CmsRoute: CmsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { createStart } from "@tanstack/react-start"

import type { getRouter } from "./router.tsx"
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
